language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

matrix:
    include:
        - php: 5.3
          dist: precise

install:
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit --coverage-text
